version: 1
events:
  hostname: "acit3855-kafka.westus.cloudapp.azure.com"
  port: 9092
  topic: "events"

datastore:
  filename: "anomalies.json"

thresholds:
  pm25_max: 400.0 # EPA standard for 24-hour PM2.5
  temperature_max: 40.0 # Celsius

scheduler:
  period_sec: 5 # Process messages every 5 seconds
