services:
  receiver:
    image: receiver
    restart: always
    environment:
      - TARGET_ENV=test
    ports:
      - "8080:8080"
    volumes:
      - /home/azureuser/config/receiver:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy

  storage:
    image: storage
    restart: always
    environment:
      - TARGET_ENV=test
    ports:
      - "8090:8090"
    volumes:
      - /home/azureuser/config/storage:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy

  processing:
    image: processing
    restart: always
    environment:
      - TARGET_ENV=test
    network_mode: "host"
    ports:
      - "8100:8100"
    volumes:
      - /home/azureuser/config/processing:/config
      - /home/azureuser/logs:/logs
      - processing-db:/data
    depends_on:
      - "storage"

  analyzer:
    image: analyzer
    restart: always
    environment:
      - TARGET_ENV=test
    ports:
      - "8110:8110"
    volumes:
      - /home/azureuser/config/analyzer:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy

  anomaly_detector:
    image: anomaly_detector
    restart: always
    environment:
      - TARGET_ENV=test
    ports:
      - "8120:8120"
    volumes:
      - /home/azureuser/config/anomaly_detector:/config
      - /home/azureuser/logs:/logs
      - anomaly-db:/data
    depends_on:
      kafka:
        condition: service_healthy

  dashboard:
    image: dashboard
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - "processing"
      - "analyzer"
      - "anomaly_detector"

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://acit3855-kafka.westus.cloudapp.azure.com:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - /home/azureuser/kafka:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 45s

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "events"
      MYSQL_USER: "roger"
      MYSQL_PASSWORD: "axl320n24h"
      MYSQL_ROOT_PASSWORD: "axl320n24h"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  my-db:
  processing-db:
  anomaly-db:
