services:
  receiver:
    image: receiver
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy

  storage:
    image: storage
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      db:
        condition: service_healthy

  processing:
    image: processing
    restart: always
    network_mode: "host"
    ports:
      - "8100:8100"
    depends_on:
      - "storage"

  analyzer:
    image: analyzer
    restart: always
    ports:
      - "8110:8110"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy

  dashboard:
    image: dashboard
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - "processing"
      - "analyzer"

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181"
    hostname: zookeeper
    healthcheck:
      test: echo mntr | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  kafka:
    image: wurstmeister/kafka
    restart: always
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_HOST_NAME: acit3855-kafka.westus.cloudapp.azure.com
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://acit3855-kafka.westus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONNECTIONS_MAX_IDLE_MS: 600000
      KAFKA_SOCKET_CONNECTION_SETUP_TIMEOUT_MS: 30000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --list --bootstrap-server localhost:9092",
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 45s

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "events"
      MYSQL_USER: "roger"
      MYSQL_PASSWORD: "axl320n24h"
      MYSQL_ROOT_PASSWORD: "axl320n24h"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  my-db:
